-- 24) Create a trigger before\after delete on the employee table for each row\statement.
CREATE OR REPLACE TRIGGER T6
BEFORE UPDATE OR DELETE OF SALARY ON EMP1
FOR EACH ROW
BEGIN
IF DELETING THEN
DBMS_OUTPUT.PUT_LINE(&#39;BEFORE DELETE TRIGGER FIRED&#39;);
END IF;
END;
/

SQL> DELETE FROM EMP1 WHERE EMPNO=6; BEFORE DELEE TRIGGER FIRED